import { assetScaleRules } from "./assetScaleRules";
import type { MapSceneLayer, RawMapPlacement } from "./mapAssetPlacement";
import type { RegionId } from "./types";

type V4MapAssetUrls = Record<string, string>;

export const placementRegionIds = [
  "growth-plaza",
  "mangrove",
  "shell-bay",
  "pearl-bay",
  "sun-town",
  "math-arena",
  "old-street",
] as const satisfies readonly RegionId[];

export type RawPlacementGroups = Record<RegionId, RawMapPlacement[]>;

export function createRawV4PlacementGroups(assets: V4MapAssetUrls): RawPlacementGroups {
  return {
    "growth-plaza": [
      {
        id: "route-main-loop",
        regionId: "growth-plaza",
        layer: "path",
        zIndex: 110,
        url: assets.routeMainLoop,
        x: 1210,
        y: 823,
        width: assetScaleRules.path.mainLoopWidth,
      },
      {
        id: "growth-tree-ring",
        regionId: "growth-plaza",
        layer: "landmark",
        zIndex: 300,
        url: assets.growthTreeRing,
        x: 1210,
        y: 805,
        width: assetScaleRules.landmark.growthTreeRingWidth,
        alpha: 0.96,
      },
      {
        id: "home-selection-plaza",
        regionId: "growth-plaza",
        layer: "landmark",
        zIndex: 420,
        url: assets.homeSelectionPlaza,
        x: 1035,
        y: 812,
        width: 230,
        alpha: 0.9,
      },
      {
        id: "teacher-review-kiosk",
        regionId: "growth-plaza",
        layer: "landmark",
        zIndex: 610,
        url: assets.teacherReviewKiosk,
        x: 1518,
        y: 748,
        width: 225,
        interactive: "dialogue",
      },
      {
        id: "growth-tree-large",
        regionId: "growth-plaza",
        layer: "landmark",
        zIndex: 760,
        url: assets.growthTreeLarge,
        x: 1210,
        y: 642,
        width: assetScaleRules.landmark.growthTreeWidth,
      },
      {
        id: "review-glow",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 210,
        url: assets.reviewGlow,
        x: 1518,
        y: 748,
        width: 165,
        alpha: 0.5,
        interactive: "dialogue",
      },
      {
        id: "edge-rock-b",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 370,
        url: assets.edgeRock,
        x: 835,
        y: 822,
        width: 74,
      },
    ],
    mangrove: [
      {
        id: "edge-grass-a",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 360,
        url: assets.edgeGrass,
        x: 338,
        y: 760,
        width: assetScaleRules.decoration.mediumClusterWidth,
      },
      {
        id: "edge-bush-a",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 374,
        url: assets.edgeBush,
        x: 432,
        y: 708,
        width: 92,
      },
    ],
    "shell-bay": [
      {
        id: "route-shell-branch",
        regionId: "shell-bay",
        layer: "path",
        zIndex: 112,
        url: assets.routeShellBranch,
        x: 660,
        y: 1055,
        width: assetScaleRules.path.residentialBranchWidth,
      },
      {
        id: "road-shell-short",
        regionId: "shell-bay",
        layer: "path",
        zIndex: 124,
        url: assets.roadShellShort,
        x: 455,
        y: 1116,
        width: 128,
        rotation: -0.3,
      },
      {
        id: "seaside-pier",
        regionId: "shell-bay",
        layer: "landmark",
        zIndex: 560,
        url: assets.seasidePier,
        x: 365,
        y: 1208,
        width: 310,
      },
      {
        id: "silver-beach-corner",
        regionId: "shell-bay",
        layer: "landmark",
        zIndex: 510,
        url: assets.silverBeachCorner,
        x: 275,
        y: 1035,
        width: 250,
      },
      {
        id: "small-fishing-boat",
        regionId: "shell-bay",
        layer: "landmark",
        zIndex: 520,
        url: assets.smallFishingBoat,
        x: 245,
        y: 1328,
        width: 165,
      },
      {
        id: "edge-flower-a",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 365,
        url: assets.edgeFlower,
        x: 488,
        y: 1142,
        width: assetScaleRules.decoration.largeClusterWidth,
      },
      {
        id: "edge-shell-a",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 370,
        url: assets.edgeShell,
        x: 540,
        y: 1190,
        width: 84,
      },
      {
        id: "edge-shell-b",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 370,
        url: assets.edgeShell,
        x: 760,
        y: 912,
        width: 76,
        rotation: 0.2,
      },
      {
        id: "area-arch-shell",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 390,
        url: assets.areaArchBlank,
        x: 530,
        y: 840,
        width: assetScaleRules.decoration.signArchWidth,
      },
    ],
    "pearl-bay": [
      {
        id: "route-stone-branch",
        regionId: "pearl-bay",
        layer: "path",
        zIndex: 112,
        url: assets.routeStoneBranch,
        x: 1668,
        y: 715,
        width: assetScaleRules.path.bayBranchWidth,
      },
      {
        id: "cliff-stair-large",
        regionId: "pearl-bay",
        layer: "path",
        zIndex: 118,
        url: assets.cliffStairLarge,
        x: 2075,
        y: 925,
        width: 285,
      },
      {
        id: "lighthouse-small",
        regionId: "pearl-bay",
        layer: "landmark",
        zIndex: 610,
        url: assets.lighthouseSmall,
        x: 2030,
        y: 650,
        width: 175,
      },
      {
        id: "edge-grass-b",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 360,
        url: assets.edgeGrass,
        x: 2074,
        y: 895,
        width: assetScaleRules.decoration.smallClusterWidth,
        rotation: 0.2,
      },
      {
        id: "edge-rock-a",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 370,
        url: assets.edgeRock,
        x: 1605,
        y: 410,
        width: 84,
      },
      {
        id: "reed-cluster-a",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 372,
        url: assets.reedCluster,
        x: 1536,
        y: 665,
        width: 92,
      },
      {
        id: "reed-cluster-b",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 372,
        url: assets.reedCluster,
        x: 1958,
        y: 725,
        width: 84,
        rotation: -0.2,
      },
    ],
    "sun-town": [
      {
        id: "road-stone-short-a",
        regionId: "sun-town",
        layer: "path",
        zIndex: 124,
        url: assets.roadStoneShort,
        x: 1560,
        y: 965,
        width: 118,
        rotation: 0.25,
      },
      {
        id: "edge-flower-b",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 365,
        url: assets.edgeFlower,
        x: 1868,
        y: 1242,
        width: assetScaleRules.decoration.largeClusterWidth,
      },
      {
        id: "edge-bush-b",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 374,
        url: assets.edgeBush,
        x: 1750,
        y: 882,
        width: 104,
      },
      {
        id: "area-arch-town",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 390,
        url: assets.areaArchBlank,
        x: 1780,
        y: 855,
        width: assetScaleRules.decoration.signArchWidth,
      },
    ],
    "math-arena": [
      {
        id: "road-t-arena",
        regionId: "math-arena",
        layer: "path",
        zIndex: 122,
        url: assets.roadJunctionT,
        x: 1235,
        y: 1046,
        width: 170,
      },
      {
        id: "pk-glow",
        regionId: "math-arena",
        layer: "decoration",
        zIndex: 210,
        url: assets.pkGlow,
        x: 1245,
        y: 1120,
        width: 290,
        alpha: 0.68,
        interactive: "pk",
      },
      {
        id: "leaderboard-stage",
        regionId: "math-arena",
        layer: "landmark",
        zIndex: 650,
        url: assets.leaderboardStage,
        x: 1468,
        y: 1245,
        width: 230,
      },
      {
        id: "math-arena-building",
        regionId: "math-arena",
        layer: "landmark",
        zIndex: 680,
        url: assets.mathArenaBuilding,
        x: 1245,
        y: 1132,
        width: assetScaleRules.landmark.mathArenaWidth,
        interactive: "pk",
        collision: { widthRatio: 0.78, heightRatio: 0.54 },
      },
      {
        id: "math-pk-gate",
        regionId: "math-arena",
        layer: "landmark",
        zIndex: 690,
        url: assets.mathPkGate,
        x: 1478,
        y: 1048,
        width: assetScaleRules.landmark.mathGateWidth,
        interactive: "pk",
        collision: { widthRatio: 0.74, heightRatio: 0.58 },
      },
    ],
    "old-street": [
      {
        id: "road-y-old-street",
        regionId: "old-street",
        layer: "path",
        zIndex: 122,
        url: assets.roadJunctionY,
        x: 1070,
        y: 540,
        width: 150,
        rotation: -0.08,
      },
      {
        id: "asr-glow",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 210,
        url: assets.asrGlow,
        x: 980,
        y: 565,
        width: 145,
        alpha: 0.55,
        interactive: "dialogue",
      },
      {
        id: "task-glow",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 210,
        url: assets.taskGlow,
        x: 1342,
        y: 542,
        width: 160,
        alpha: 0.46,
        interactive: "dialogue",
      },
      {
        id: "old-street-shop-row",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 615,
        url: assets.oldStreetShopRow,
        x: 1168,
        y: 412,
        width: assetScaleRules.landmark.oldStreetShopRowWidth,
      },
      {
        id: "old-street-arch",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 620,
        url: assets.oldStreetArch,
        x: 895,
        y: 425,
        width: assetScaleRules.landmark.oldStreetArchWidth,
        interactive: "dialogue",
        collision: { widthRatio: 0.72, heightRatio: 0.62 },
      },
      {
        id: "arcade-lantern-row",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 625,
        url: assets.arcadeLanternRow,
        x: 1118,
        y: 520,
        width: 260,
      },
      {
        id: "dialogue-pavilion",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 630,
        url: assets.dialoguePavilion,
        x: 1415,
        y: 500,
        width: 240,
        interactive: "dialogue",
        collision: { widthRatio: 0.72, heightRatio: 0.58 },
      },
      {
        id: "asr-corner",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 632,
        url: assets.asrRecordingCorner,
        x: 980,
        y: 565,
        width: 205,
        interactive: "dialogue",
      },
      {
        id: "task-board",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 634,
        url: assets.taskBoard,
        x: 1342,
        y: 542,
        width: 205,
        interactive: "dialogue",
      },
    ],
  };
}

export function rawPlacementsByLayer(groups: RawPlacementGroups, layer: MapSceneLayer) {
  return placementRegionIds.flatMap((regionId) => groups[regionId].filter((placement) => placement.layer === layer));
}

export function allRawPlacements(groups: RawPlacementGroups) {
  return placementRegionIds.flatMap((regionId) => groups[regionId]);
}
