/**
 * [INPUT]: 依赖 assetScaleRules 的地图缩放规则，依赖 mapAssetPlacement 的 RawMapPlacement 类型。
 * [OUTPUT]: 对外提供 growth-plaza 区域原始 placement 列表。
 * [POS]: game/mapPlacements 的成长广场数据 Module，被 mapPlacementConfig 聚合。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */

import { assetScaleRules } from "../assetScaleRules";
import type { RawMapPlacement } from "../mapAssetPlacement";

type V4MapAssetUrls = Record<string, string>;

export function createGrowthPlacements(assets: V4MapAssetUrls): RawMapPlacement[] {
  return [
      {
        id: "route-main-loop",
        regionId: "growth-plaza",
        layer: "path",
        zIndex: 110,
        url: assets.routeMainLoop,
        x: 1210,
        y: 823,
        width: assetScaleRules.path.mainLoopWidth,
      },
      {
        id: "growth-tree-ring",
        regionId: "growth-plaza",
        layer: "landmark",
        zIndex: 300,
        url: assets.growthTreeRing,
        x: 1210,
        y: 805,
        width: assetScaleRules.landmark.growthTreeRingWidth,
        alpha: 0.96,
      },
      {
        id: "home-selection-plaza",
        regionId: "growth-plaza",
        layer: "landmark",
        zIndex: 420,
        url: assets.homeSelectionPlaza,
        x: 1035,
        y: 812,
        width: 230,
        alpha: 0.9,
      },
      {
        id: "teacher-review-kiosk",
        regionId: "growth-plaza",
        layer: "landmark",
        zIndex: 610,
        url: assets.teacherReviewKiosk,
        x: 1518,
        y: 748,
        width: 225,
        interactive: "dialogue",
      },
      {
        id: "growth-tree-large",
        regionId: "growth-plaza",
        layer: "landmark",
        zIndex: 760,
        url: assets.growthTreeLarge,
        x: 1210,
        y: 642,
        width: assetScaleRules.landmark.growthTreeWidth,
      },
      {
        id: "review-glow",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 210,
        url: assets.reviewGlow,
        x: 1518,
        y: 748,
        width: 165,
        alpha: 0.5,
        interactive: "dialogue",
      },
      {
        id: "edge-rock-b",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 370,
        url: assets.edgeRock,
        x: 835,
        y: 822,
        width: 74,
      },
      {
        id: "p15-growth-tree",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 585,
        url: assets.p15PropTree,
        x: 962,
        y: 710,
        width: 72,
        interactive: "self-service",
        collision: { widthRatio: 1.36, heightRatio: 1.24 },
      },
      {
        id: "p15-growth-rock",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 372,
        url: assets.p15PropRock1,
        x: 852,
        y: 820,
        width: 48,
        rotation: -0.12,
      },
      {
        id: "p15-growth-fence-corner",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 392,
        url: assets.p15PropFenceCorner,
        x: 1395,
        y: 790,
        width: 70,
        rotation: 0.18,
      },
      {
        id: "p16-growth-house-1",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 606,
        url: assets.p16PropHouse1,
        x: 1018,
        y: 890,
        width: 86,
      },
      {
        id: "p16-growth-bench-1",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 404,
        url: assets.p16PropBench1,
        x: 1088,
        y: 905,
        width: 68,
        rotation: -0.14,
      },
      {
        id: "p16-growth-heart",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 405,
        url: assets.p16PropHeart,
        x: 1116,
        y: 790,
        width: 52,
        interactive: "self-service",
        collision: { widthRatio: 1.45, heightRatio: 1.32 },
      },
      {
        id: "p19-growth-star-pad",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 407,
        url: assets.p16PropStarOutline,
        x: 1168,
        y: 832,
        width: 58,
        rotation: -0.08,
      },
      {
        id: "p16-growth-fruit",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 406,
        url: assets.p16PropFruit,
        x: 990,
        y: 780,
        width: 42,
        rotation: 0.14,
      },
      {
        id: "p16-growth-stairs-start",
        regionId: "growth-plaza",
        layer: "decoration",
        zIndex: 394,
        url: assets.p16PropStairsModularStart,
        x: 1340,
        y: 826,
        width: 80,
        rotation: 0.1,
      },
  ];
}
