/**
 * [INPUT]: 依赖 assetScaleRules 的地图缩放规则，依赖 mapAssetPlacement 的 RawMapPlacement 类型。
 * [OUTPUT]: 对外提供小屋相关海湾/红树林区域原始 placement 列表。
 * [POS]: game/mapPlacements 的小屋区域数据 Module，被 mapPlacementConfig 聚合。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */

import { assetScaleRules } from "../assetScaleRules";
import type { RawMapPlacement } from "../mapAssetPlacement";

type V4MapAssetUrls = Record<string, string>;

export function createMangrovePlacements(assets: V4MapAssetUrls): RawMapPlacement[] {
  return [
      {
        id: "edge-grass-a",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 360,
        url: assets.edgeGrass,
        x: 338,
        y: 760,
        width: assetScaleRules.decoration.mediumClusterWidth,
      },
      {
        id: "edge-bush-a",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 374,
        url: assets.edgeBush,
        x: 432,
        y: 708,
        width: 92,
      },
      {
        id: "p15-mangrove-tree-fruit",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 590,
        url: assets.p15PropTreeFruit,
        x: 595,
        y: 508,
        width: 88,
      },
      {
        id: "p15-mangrove-bush",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 382,
        url: assets.p15PropBush,
        x: 430,
        y: 720,
        width: 70,
      },
      {
        id: "p15-mangrove-grass",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 384,
        url: assets.p15PropGrass1,
        x: 850,
        y: 670,
        width: 56,
        rotation: 0.18,
      },
      {
        id: "p15-mangrove-bridge",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 386,
        url: assets.p15PropBridgeSmall,
        x: 575,
        y: 735,
        width: 116,
        rotation: -0.12,
      },
      {
        id: "p16-mangrove-house-2",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 604,
        url: assets.p16PropHouse2,
        x: 530,
        y: 632,
        width: 86,
      },
      {
        id: "p16-mangrove-grass-3",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 385,
        url: assets.p16PropGrass3,
        x: 790,
        y: 708,
        width: 54,
        rotation: -0.12,
      },
      {
        id: "p16-mangrove-rock-platform-1",
        regionId: "mangrove",
        layer: "decoration",
        zIndex: 383,
        url: assets.p16PropRockPlatform1,
        x: 725,
        y: 785,
        width: 72,
        rotation: 0.1,
      },
  ];
}

export function createShellBayPlacements(assets: V4MapAssetUrls): RawMapPlacement[] {
  return [
      {
        id: "route-shell-branch",
        regionId: "shell-bay",
        layer: "path",
        zIndex: 112,
        url: assets.routeShellBranch,
        x: 660,
        y: 1055,
        width: assetScaleRules.path.residentialBranchWidth,
      },
      {
        id: "road-shell-short",
        regionId: "shell-bay",
        layer: "path",
        zIndex: 124,
        url: assets.roadShellShort,
        x: 455,
        y: 1116,
        width: 128,
        rotation: -0.3,
      },
      {
        id: "seaside-pier",
        regionId: "shell-bay",
        layer: "landmark",
        zIndex: 560,
        url: assets.seasidePier,
        x: 365,
        y: 1208,
        width: 310,
      },
      {
        id: "silver-beach-corner",
        regionId: "shell-bay",
        layer: "landmark",
        zIndex: 510,
        url: assets.silverBeachCorner,
        x: 275,
        y: 1035,
        width: 250,
      },
      {
        id: "small-fishing-boat",
        regionId: "shell-bay",
        layer: "landmark",
        zIndex: 520,
        url: assets.smallFishingBoat,
        x: 245,
        y: 1328,
        width: 165,
      },
      {
        id: "edge-flower-a",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 365,
        url: assets.edgeFlower,
        x: 488,
        y: 1142,
        width: assetScaleRules.decoration.largeClusterWidth,
      },
      {
        id: "edge-shell-a",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 370,
        url: assets.edgeShell,
        x: 540,
        y: 1190,
        width: 84,
      },
      {
        id: "edge-shell-b",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 370,
        url: assets.edgeShell,
        x: 760,
        y: 912,
        width: 76,
        rotation: 0.2,
      },
      {
        id: "area-arch-shell",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 390,
        url: assets.areaArchBlank,
        x: 530,
        y: 840,
        width: assetScaleRules.decoration.signArchWidth,
      },
      {
        id: "p15-shell-bush-fruit",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 386,
        url: assets.p15PropBushFruit,
        x: 785,
        y: 1010,
        width: 70,
      },
      {
        id: "p15-shell-grass",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 384,
        url: assets.p15PropGrass2,
        x: 595,
        y: 1155,
        width: 54,
        rotation: -0.2,
      },
      {
        id: "p15-shell-bridge",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 388,
        url: assets.p15PropBridgeModular,
        x: 695,
        y: 1035,
        width: 125,
        rotation: 0.14,
      },
      {
        id: "p15-shell-fence",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 392,
        url: assets.p15PropFenceMiddle,
        x: 710,
        y: 1170,
        width: 82,
        rotation: 0.16,
      },
      {
        id: "p16-shell-house-3",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 604,
        url: assets.p16PropHouse3,
        x: 540,
        y: 965,
        width: 86,
      },
      {
        id: "p16-shell-gazebo",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 588,
        url: assets.p16PropGazebo,
        x: 625,
        y: 1060,
        width: 82,
      },
      {
        id: "p16-shell-bench-2",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 394,
        url: assets.p16PropBench2,
        x: 455,
        y: 995,
        width: 68,
        rotation: 0.18,
      },
      {
        id: "p16-shell-rock-platform-2",
        regionId: "shell-bay",
        layer: "decoration",
        zIndex: 383,
        url: assets.p16PropRockPlatform2,
        x: 835,
        y: 930,
        width: 72,
        rotation: -0.08,
      },
  ];
}

export function createPearlBayPlacements(assets: V4MapAssetUrls): RawMapPlacement[] {
  return [
      {
        id: "route-stone-branch",
        regionId: "pearl-bay",
        layer: "path",
        zIndex: 112,
        url: assets.routeStoneBranch,
        x: 1668,
        y: 715,
        width: assetScaleRules.path.bayBranchWidth,
      },
      {
        id: "cliff-stair-large",
        regionId: "pearl-bay",
        layer: "path",
        zIndex: 118,
        url: assets.cliffStairLarge,
        x: 2075,
        y: 925,
        width: 285,
      },
      {
        id: "lighthouse-small",
        regionId: "pearl-bay",
        layer: "landmark",
        zIndex: 610,
        url: assets.lighthouseSmall,
        x: 2030,
        y: 650,
        width: 175,
      },
      {
        id: "edge-grass-b",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 360,
        url: assets.edgeGrass,
        x: 2074,
        y: 895,
        width: assetScaleRules.decoration.smallClusterWidth,
        rotation: 0.2,
      },
      {
        id: "edge-rock-a",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 370,
        url: assets.edgeRock,
        x: 1605,
        y: 410,
        width: 84,
      },
      {
        id: "reed-cluster-a",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 372,
        url: assets.reedCluster,
        x: 1536,
        y: 665,
        width: 92,
      },
      {
        id: "reed-cluster-b",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 372,
        url: assets.reedCluster,
        x: 1958,
        y: 725,
        width: 84,
        rotation: -0.2,
      },
      {
        id: "p15-pearl-rock",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 378,
        url: assets.p15PropRock2,
        x: 1840,
        y: 632,
        width: 52,
      },
      {
        id: "p15-pearl-plant",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 382,
        url: assets.p15PropPlantLarge,
        x: 1958,
        y: 725,
        width: 60,
        rotation: -0.18,
      },
      {
        id: "p15-pearl-gem-blue",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 396,
        url: assets.p15PropGemBlue,
        x: 1665,
        y: 690,
        width: 46,
      },
      {
        id: "p16-pearl-house-4",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 604,
        url: assets.p16PropHouse4,
        x: 1760,
        y: 575,
        width: 86,
      },
      {
        id: "p16-pearl-rock-platform-large",
        regionId: "pearl-bay",
        layer: "decoration",
        zIndex: 384,
        url: assets.p16PropRockPlatformLarge,
        x: 2018,
        y: 838,
        width: 86,
        rotation: 0.12,
      },
  ];
}
