/**
 * [INPUT]: 依赖 assetScaleRules 的地图缩放规则，依赖 mapAssetPlacement 的 RawMapPlacement 类型。
 * [OUTPUT]: 对外提供荣誉/课堂挑战区域原始 placement 列表。
 * [POS]: game/mapPlacements 的荣誉区域数据 Module，被 mapPlacementConfig 聚合。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */

import { assetScaleRules } from "../assetScaleRules";
import type { RawMapPlacement } from "../mapAssetPlacement";

type V4MapAssetUrls = Record<string, string>;

export function createSunTownPlacements(assets: V4MapAssetUrls): RawMapPlacement[] {
  return [
      {
        id: "road-stone-short-a",
        regionId: "sun-town",
        layer: "path",
        zIndex: 124,
        url: assets.roadStoneShort,
        x: 1560,
        y: 965,
        width: 118,
        rotation: 0.25,
      },
      {
        id: "edge-flower-b",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 365,
        url: assets.edgeFlower,
        x: 1868,
        y: 1242,
        width: assetScaleRules.decoration.largeClusterWidth,
      },
      {
        id: "edge-bush-b",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 374,
        url: assets.edgeBush,
        x: 1750,
        y: 882,
        width: 104,
      },
      {
        id: "area-arch-town",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 390,
        url: assets.areaArchBlank,
        x: 1780,
        y: 855,
        width: assetScaleRules.decoration.signArchWidth,
      },
      {
        id: "p15-town-door",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 586,
        url: assets.p15PropDoor,
        x: 1840,
        y: 970,
        width: 58,
      },
      {
        id: "p15-town-fence",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 392,
        url: assets.p15PropFence1,
        x: 1660,
        y: 1080,
        width: 76,
        rotation: -0.18,
      },
      {
        id: "p15-town-plant",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 384,
        url: assets.p15PropPlantSmall,
        x: 1590,
        y: 920,
        width: 52,
        rotation: 0.16,
      },
      {
        id: "p16-town-stable",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 606,
        url: assets.p16PropStable,
        x: 1815,
        y: 1040,
        width: 96,
        rotation: -0.08,
      },
      {
        id: "p16-town-fence",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 393,
        url: assets.p16PropFence,
        x: 1700,
        y: 1010,
        width: 74,
        rotation: 0.18,
      },
      {
        id: "p16-town-stairs",
        regionId: "sun-town",
        layer: "decoration",
        zIndex: 386,
        url: assets.p16PropStairs,
        x: 1540,
        y: 1045,
        width: 76,
        rotation: -0.12,
      },
  ];
}

export function createMathArenaPlacements(assets: V4MapAssetUrls): RawMapPlacement[] {
  return [
      {
        id: "road-t-arena",
        regionId: "math-arena",
        layer: "path",
        zIndex: 122,
        url: assets.roadJunctionT,
        x: 1235,
        y: 1046,
        width: 170,
      },
      {
        id: "pk-glow",
        regionId: "math-arena",
        layer: "decoration",
        zIndex: 210,
        url: assets.pkGlow,
        x: 1245,
        y: 1120,
        width: 290,
        alpha: 0.68,
        interactive: "pk",
      },
      {
        id: "leaderboard-stage",
        regionId: "math-arena",
        layer: "landmark",
        zIndex: 650,
        url: assets.leaderboardStage,
        x: 1468,
        y: 1245,
        width: 230,
      },
      {
        id: "p15-honor-star",
        regionId: "math-arena",
        layer: "landmark",
        zIndex: 655,
        url: assets.p15PropStar,
        x: 1415,
        y: 1190,
        width: 64,
        interactive: "leaderboard",
        collision: { widthRatio: 1.25, heightRatio: 1.15 },
      },
      {
        id: "p15-honor-flag",
        regionId: "math-arena",
        layer: "landmark",
        zIndex: 656,
        url: assets.p15PropGoalFlag,
        x: 1558,
        y: 1195,
        width: 66,
        interactive: "leaderboard",
        collision: { widthRatio: 1.22, heightRatio: 1.25 },
      },
      {
        id: "p15-honor-stairs",
        regionId: "math-arena",
        layer: "decoration",
        zIndex: 392,
        url: assets.p15PropStairsSmall,
        x: 1455,
        y: 1290,
        width: 80,
        rotation: 0.08,
      },
      {
        id: "p16-honor-bell-tower",
        regionId: "math-arena",
        layer: "landmark",
        zIndex: 658,
        url: assets.p16PropBellTower,
        x: 1605,
        y: 1236,
        width: 78,
        interactive: "leaderboard",
        collision: { widthRatio: 1.22, heightRatio: 1.35 },
      },
      {
        id: "p16-honor-bell",
        regionId: "math-arena",
        layer: "landmark",
        zIndex: 657,
        url: assets.p16PropBell,
        x: 1510,
        y: 1165,
        width: 58,
        interactive: "leaderboard",
        collision: { widthRatio: 1.3, heightRatio: 1.25 },
      },
      {
        id: "p16-honor-star-outline",
        regionId: "math-arena",
        layer: "decoration",
        zIndex: 393,
        url: assets.p16PropStarOutline,
        x: 1370,
        y: 1234,
        width: 44,
      },
      {
        id: "p16-honor-heart-outline",
        regionId: "math-arena",
        layer: "decoration",
        zIndex: 394,
        url: assets.p16PropHeartOutline,
        x: 1468,
        y: 1168,
        width: 44,
      },
      {
        id: "p16-honor-tower",
        regionId: "math-arena",
        layer: "decoration",
        zIndex: 395,
        url: assets.p16PropTower,
        x: 1540,
        y: 1308,
        width: 58,
      },
      {
        id: "math-arena-building",
        regionId: "math-arena",
        layer: "landmark",
        zIndex: 680,
        url: assets.mathArenaBuilding,
        x: 1245,
        y: 1132,
        width: assetScaleRules.landmark.mathArenaWidth,
        interactive: "pk",
        collision: { widthRatio: 0.78, heightRatio: 0.54 },
      },
      {
        id: "math-pk-gate",
        regionId: "math-arena",
        layer: "landmark",
        zIndex: 690,
        url: assets.mathPkGate,
        x: 1478,
        y: 1048,
        width: assetScaleRules.landmark.mathGateWidth,
        interactive: "pk",
        collision: { widthRatio: 0.74, heightRatio: 0.58 },
      },
  ];
}
