/**
 * [INPUT]: 依赖 assetScaleRules 的地图缩放规则，依赖 mapAssetPlacement 的 RawMapPlacement 类型。
 * [OUTPUT]: 对外提供小铺/旧街区域原始 placement 列表。
 * [POS]: game/mapPlacements 的小铺区域数据 Module，被 mapPlacementConfig 聚合。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */

import { assetScaleRules } from "../assetScaleRules";
import type { RawMapPlacement } from "../mapAssetPlacement";

type V4MapAssetUrls = Record<string, string>;

export function createOldStreetPlacements(assets: V4MapAssetUrls): RawMapPlacement[] {
  return [
      {
        id: "road-y-old-street",
        regionId: "old-street",
        layer: "path",
        zIndex: 122,
        url: assets.roadJunctionY,
        x: 1070,
        y: 540,
        width: 150,
        rotation: -0.08,
      },
      {
        id: "asr-glow",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 210,
        url: assets.asrGlow,
        x: 980,
        y: 565,
        width: 145,
        alpha: 0.55,
        interactive: "dialogue",
      },
      {
        id: "task-glow",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 210,
        url: assets.taskGlow,
        x: 1342,
        y: 542,
        width: 160,
        alpha: 0.46,
        interactive: "dialogue",
      },
      {
        id: "old-street-shop-row",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 615,
        url: assets.oldStreetShopRow,
        x: 1168,
        y: 412,
        width: assetScaleRules.landmark.oldStreetShopRowWidth,
      },
      {
        id: "p15-shop-chest",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 636,
        url: assets.p15PropChest,
        x: 1205,
        y: 545,
        width: 88,
        interactive: "shop",
        collision: { widthRatio: 1.25, heightRatio: 1.05 },
      },
      {
        id: "p15-shop-key",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 396,
        url: assets.p15PropKey,
        x: 1180,
        y: 500,
        width: 54,
      },
      {
        id: "p15-shop-coin",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 397,
        url: assets.p15PropCoin,
        x: 1265,
        y: 556,
        width: 50,
      },
      {
        id: "p15-shop-gem-green",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 398,
        url: assets.p15PropGemGreen,
        x: 1125,
        y: 555,
        width: 50,
      },
      {
        id: "p15-shop-gem-pink",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 399,
        url: assets.p15PropGemPink,
        x: 1305,
        y: 505,
        width: 50,
      },
      {
        id: "p16-shop-market-stand-1",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 638,
        url: assets.p16PropMarketStand1,
        x: 1072,
        y: 512,
        width: 102,
        interactive: "shop",
        collision: { widthRatio: 1.2, heightRatio: 1.0 },
      },
      {
        id: "p16-shop-market-stand-2",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 639,
        url: assets.p16PropMarketStand2,
        x: 1290,
        y: 455,
        width: 98,
        interactive: "shop",
        collision: { widthRatio: 1.22, heightRatio: 1.0 },
      },
      {
        id: "p16-shop-cart",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 402,
        url: assets.p16PropCart,
        x: 1320,
        y: 600,
        width: 72,
        rotation: -0.1,
      },
      {
        id: "p16-shop-barrel",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 403,
        url: assets.p16PropBarrel,
        x: 1120,
        y: 470,
        width: 42,
      },
      {
        id: "p16-shop-crate",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 404,
        url: assets.p16PropCrate,
        x: 1240,
        y: 470,
        width: 44,
        rotation: 0.08,
      },
      {
        id: "p16-shop-bags",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 405,
        url: assets.p16PropBags,
        x: 1098,
        y: 595,
        width: 48,
      },
      {
        id: "p16-shop-bag-open",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 406,
        url: assets.p16PropBagOpen,
        x: 1160,
        y: 610,
        width: 44,
        rotation: -0.1,
      },
      {
        id: "p16-shop-package-1",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 407,
        url: assets.p16PropPackage1,
        x: 1292,
        y: 575,
        width: 44,
      },
      {
        id: "p16-shop-package-2",
        regionId: "old-street",
        layer: "decoration",
        zIndex: 408,
        url: assets.p16PropPackage2,
        x: 1360,
        y: 555,
        width: 46,
        rotation: 0.12,
      },
      {
        id: "old-street-arch",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 620,
        url: assets.oldStreetArch,
        x: 895,
        y: 425,
        width: assetScaleRules.landmark.oldStreetArchWidth,
        interactive: "dialogue",
        collision: { widthRatio: 0.72, heightRatio: 0.62 },
      },
      {
        id: "arcade-lantern-row",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 625,
        url: assets.arcadeLanternRow,
        x: 1118,
        y: 520,
        width: 260,
      },
      {
        id: "dialogue-pavilion",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 630,
        url: assets.dialoguePavilion,
        x: 1415,
        y: 500,
        width: 240,
        interactive: "dialogue",
        collision: { widthRatio: 0.72, heightRatio: 0.58 },
      },
      {
        id: "asr-corner",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 632,
        url: assets.asrRecordingCorner,
        x: 980,
        y: 565,
        width: 205,
        interactive: "dialogue",
      },
      {
        id: "task-board",
        regionId: "old-street",
        layer: "landmark",
        zIndex: 634,
        url: assets.taskBoard,
        x: 1342,
        y: 542,
        width: 205,
        interactive: "dialogue",
      },
  ];
}
